import { IdentityColour } from "./IdentityColour";

export enum IdentityLabel {
  WHITE = "Mono-White (W)",
  BLUE = "Mono-Blue (U)",
  BLACK = "Mono-Black (B)",
  RED = "Mono-Red (R)",
  GREEN = "Mono-Green (G)",
  COLORLESS = "Colorless (C)",
  GRIXIS = "Grixis (UBR)",
  DIMIR = "Dimir (UB)",
  JESKAI = "Jeskai (WUR)",
  BANT = "Bant (WUG)",
  ESPER = "Esper (WUB)",
  NAYA = "Naya (WRG)",
  MARDU = "Mardu (WBR)",
  ABZAN = "Abzan (WBG)",
  TEMUR = "Temur (URG)",
  SULTAI = "Sultai (UBG)",
  JUND = "Jund (BRG)",
  SIMIC = "Simic (UG)",
  SELESNYA = "Selesnya (WG)",
  RAKDOS = "Rakdos (BR)",
  ORZHOV = "Orzhov (WB)",
  IZZET = "Izzet (UR)",
  GRUUL = "Gruul (RG)",
  GOLGARI = "Golgari (BG)",
  BOROS = "Boros (WR)",
  AZORIUS = "Azorius (WU)",
  FIVE_COLOR = "Five-Color (WUBRG)",
}

export const IDENTITY_LABEL_MAP: { [key in IdentityLabel]: IdentityColour[] } =
  {
    [IdentityLabel.WHITE]: [IdentityColour.WHITE],
    [IdentityLabel.BLUE]: [IdentityColour.BLUE],
    [IdentityLabel.BLACK]: [IdentityColour.BLACK],
    [IdentityLabel.RED]: [IdentityColour.RED],
    [IdentityLabel.GREEN]: [IdentityColour.GREEN],
    [IdentityLabel.COLORLESS]: [],
    [IdentityLabel.GRIXIS]: [
      IdentityColour.BLUE,
      IdentityColour.BLACK,
      IdentityColour.RED,
    ],
    [IdentityLabel.DIMIR]: [IdentityColour.BLUE, IdentityColour.BLACK],
    [IdentityLabel.JESKAI]: [
      IdentityColour.WHITE,
      IdentityColour.BLUE,
      IdentityColour.RED,
    ],
    [IdentityLabel.BANT]: [
      IdentityColour.WHITE,
      IdentityColour.GREEN,
      IdentityColour.BLUE,
    ],
    [IdentityLabel.ESPER]: [
      IdentityColour.WHITE,
      IdentityColour.BLUE,
      IdentityColour.BLACK,
    ],
    [IdentityLabel.NAYA]: [
      IdentityColour.WHITE,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.MARDU]: [
      IdentityColour.WHITE,
      IdentityColour.BLACK,
      IdentityColour.RED,
    ],
    [IdentityLabel.ABZAN]: [
      IdentityColour.WHITE,
      IdentityColour.BLACK,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.TEMUR]: [
      IdentityColour.BLUE,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.SULTAI]: [
      IdentityColour.BLUE,
      IdentityColour.BLACK,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.JUND]: [
      IdentityColour.BLACK,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.SIMIC]: [IdentityColour.BLUE, IdentityColour.GREEN],
    [IdentityLabel.SELESNYA]: [IdentityColour.WHITE, IdentityColour.GREEN],
    [IdentityLabel.RAKDOS]: [IdentityColour.RED, IdentityColour.BLACK],
    [IdentityLabel.ORZHOV]: [IdentityColour.WHITE, IdentityColour.BLACK],
    [IdentityLabel.IZZET]: [IdentityColour.BLUE, IdentityColour.RED],
    [IdentityLabel.GRUUL]: [IdentityColour.RED, IdentityColour.GREEN],
    [IdentityLabel.GOLGARI]: [IdentityColour.BLACK, IdentityColour.GREEN],
    [IdentityLabel.BOROS]: [IdentityColour.RED, IdentityColour.WHITE],
    [IdentityLabel.AZORIUS]: [IdentityColour.WHITE, IdentityColour.BLUE],
    [IdentityLabel.FIVE_COLOR]: [
      IdentityColour.WHITE,
      IdentityColour.BLUE,
      IdentityColour.BLACK,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
  };
