import { IdentityColour } from "./IdentityColour";

export enum IdentityLabel {
  WHITE = "Mono-White",
  BLUE = "Mono-Blue",
  BLACK = "Mono-Black",
  RED = "Mono-Red",
  GREEN = "Mono-Green",
  COLORLESS = "Colorless",
  GRIXIS = "Grixis",
  DIMIR = "Dimir",
  JESKAI = "Jeskai",
  BANT = "Bant",
  ESPER = "Esper",
  NAYA = "Naya",
  MARDU = "Mardu",
  ABZAN = "Abzan",
  TEMUR = "Temur",
  SULTAI = "Sultai",
  JUND = "Jund",
  SIMIC = "Simic",
  SELESNYA = "Selesnya",
  RAKDOS = "Rakdos",
  ORZHOV = "Orzhov",
  IZZET = "Izzet",
  GRUUL = "Gruul",
  GOLGARI = "Golgari",
  BOROS = "Boros",
  AZORIUS = "Azorius",
  FIVE_COLOR = "Five-Color",
}

export const IDENTITY_LABEL_MAP: { [key in IdentityLabel]: IdentityColour[] } =
  {
    [IdentityLabel.WHITE]: [IdentityColour.WHITE],
    [IdentityLabel.BLUE]: [IdentityColour.BLUE],
    [IdentityLabel.BLACK]: [IdentityColour.BLACK],
    [IdentityLabel.RED]: [IdentityColour.RED],
    [IdentityLabel.GREEN]: [IdentityColour.GREEN],
    [IdentityLabel.COLORLESS]: [],
    [IdentityLabel.GRIXIS]: [
      IdentityColour.BLUE,
      IdentityColour.BLACK,
      IdentityColour.RED,
    ],
    [IdentityLabel.DIMIR]: [IdentityColour.BLUE, IdentityColour.BLACK],
    [IdentityLabel.JESKAI]: [
      IdentityColour.WHITE,
      IdentityColour.BLUE,
      IdentityColour.RED,
    ],
    [IdentityLabel.BANT]: [
      IdentityColour.WHITE,
      IdentityColour.GREEN,
      IdentityColour.BLUE,
    ],
    [IdentityLabel.ESPER]: [
      IdentityColour.WHITE,
      IdentityColour.BLUE,
      IdentityColour.BLACK,
    ],
    [IdentityLabel.NAYA]: [
      IdentityColour.WHITE,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.MARDU]: [
      IdentityColour.WHITE,
      IdentityColour.BLACK,
      IdentityColour.RED,
    ],
    [IdentityLabel.ABZAN]: [
      IdentityColour.WHITE,
      IdentityColour.BLACK,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.TEMUR]: [
      IdentityColour.BLUE,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.SULTAI]: [
      IdentityColour.BLUE,
      IdentityColour.BLACK,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.JUND]: [
      IdentityColour.BLACK,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
    [IdentityLabel.SIMIC]: [IdentityColour.BLUE, IdentityColour.GREEN],
    [IdentityLabel.SELESNYA]: [IdentityColour.WHITE, IdentityColour.GREEN],
    [IdentityLabel.RAKDOS]: [IdentityColour.RED, IdentityColour.BLACK],
    [IdentityLabel.ORZHOV]: [IdentityColour.WHITE, IdentityColour.BLACK],
    [IdentityLabel.IZZET]: [IdentityColour.BLUE, IdentityColour.RED],
    [IdentityLabel.GRUUL]: [IdentityColour.RED, IdentityColour.GREEN],
    [IdentityLabel.GOLGARI]: [IdentityColour.BLACK, IdentityColour.GREEN],
    [IdentityLabel.BOROS]: [IdentityColour.RED, IdentityColour.WHITE],
    [IdentityLabel.AZORIUS]: [IdentityColour.WHITE, IdentityColour.BLUE],
    [IdentityLabel.FIVE_COLOR]: [
      IdentityColour.WHITE,
      IdentityColour.BLUE,
      IdentityColour.BLACK,
      IdentityColour.RED,
      IdentityColour.GREEN,
    ],
  };
