export enum PlayerSortFctKey {
  NAME_ASC = "name-asc",
  NAME_DESC = "name-desc",
  GAMES_PLAYED_ASC = "games-played-asc",
  GAMES_PLAYED_DESC = "games-played-desc",
  WIN_COUNT_ASC = "win-count-asc",
  WIN_COUNT_DESC = "win-count-desc",
  WIN_RATE_ASC = "win-rate-asc",
  WIN_RATE_DESC = "win-rate-desc",
  START_COUNT_ASC = "start-count-asc",
  START_COUNT_DESC = "start-count-desc",
  START_RATE_ASC = "start-rate-asc",
  START_RATE_DESC = "start-rate-desc",
  START_TO_WIN_RATE_ASC = "start-to-win-rate-asc",
  START_TO_WIN_RATE_DESC = "start-to-win-rate-desc",
  SOL_RING_COUNT_ASC = "sol-ring-count-asc",
  SOL_RING_COUNT_DESC = "sol-ring-count-desc",
  SOL_RING_RATE_ASC = "sol-ring-rate-asc",
  SOL_RING_RATE_DESC = "sol-ring-rate-desc",
  SOL_RING_TO_WIN_RATE_ASC = "sol-ring-to-win-rate-asc",
  SOL_RING_TO_WIN_RATE_DESC = "sol-ring-to-win-rate-desc",
  GRAND_SLAM_COUNT_ASC = "grand-slam-count-asc",
  GRAND_SLAM_COUNT_DESC = "grand-slam-count-desc",
}
